### ISSUE TITLE
I want to set up a local passport strategy with user sessions

### ISSUE THREAD

**Issue by mr-jackpot** [mr-jackpot/mern-user-auth#5]

**Comment by JordT** [comment]
State of the Union (SOTU).

Post to /auth returns an authenticated user object and req.isAuthenticated() returns a true of false boolean. This is good!

Issues to think around

- How does the backend restrict routing access based on session (cookie)
- How do we stop the front end routing without authentication
- How can the backend serve up a react page? Does it need to be a "View"

**Comment by JordT** [comment]
closed w/ #14
